# -*- coding: utf-8 -*-
"""Catálogo de pruebas y registro ampliado de riesgos."""

# ---- casos de prueba: (id, técnica, módulo, entrada o condición, resultado esperado, ejecuta, tarea)
CAJA_BLANCA = [
 ("CB-01","Cobertura de decisiones","DG.2 identificación de la pieza golpeada",
  "Colisión sobre cada uno de los seis componentes: tarola, bombo, dos toms, hi-hat y platillo",
  "La rama correspondiente a cada componente se ejecuta al menos una vez y devuelve su identificador correcto","Misael","QT.6"),
 ("CB-02","Análisis de valores límite","DG.5 niveles de intensidad",
  "Velocidad justo por debajo, igual y justo por encima de cada umbral entre suave, media y fuerte",
  "La clasificación cambia exactamente en el umbral, sin zona muerta ni solapamiento entre niveles","Misael","QT.6"),
 ("CB-03","Cobertura de condiciones","DG.6 supresión de golpes duplicados",
  "Dos colisiones separadas por menos, igual y más tiempo que la ventana de supresión",
  "Se registra un solo golpe en los dos primeros casos y dos golpes en el tercero","Misael","QT.6"),
 ("CB-04","Cobertura de sentencias","DG.4 conversión de velocidad a intensidad",
  "Velocidad cero, negativa, máxima esperada y por encima del máximo",
  "Ninguna sentencia queda sin ejecutar. Los valores fuera de rango se acotan sin lanzar excepción","Misael","QT.6"),
 ("CB-05","Cobertura de caminos","DG.7 evento DrumHit",
  "Golpe con baqueta izquierda y con baqueta derecha sobre cada componente",
  "El evento transporta instrumento, intensidad y marca de tiempo correctos en todos los caminos","Misael","QT.6"),
 ("CB-06","Complejidad ciclomática","Módulo DG completo",
  "Medición de la complejidad de cada función y diseño de casos hasta cubrir los caminos independientes",
  "La complejidad se mantiene por debajo de diez por función. Si la supera, la función se divide","Misael","QT.6"),
 ("CB-07","Prueba unitaria","JT.1 reloj musical independiente de la tasa de cuadros",
  "Ejecutar el reloj con la tasa de cuadros forzada a 30, 72 y 90",
  "El tiempo musical transcurrido no varía con la tasa de cuadros. La deriva se mantiene por debajo de 5 ms en tres minutos","Benjamín","QT.7"),
 ("CB-08","Cobertura de decisiones","JT.2 cálculo de tempo y duración de beat",
  "Tempos de 60, 90, 120 y 180 pulsos por minuto",
  "La duración de beat calculada corresponde a 60000 dividido entre el tempo, en milisegundos, en los cuatro casos","Benjamín","QT.7"),
 ("CB-09","Análisis de valores límite","JW ventanas de precisión",
  "Golpe en el centro de la ventana, en el borde exacto y un milisegundo fuera",
  "Clasificación correcta en cada caso. El borde pertenece a una sola categoría, sin ambigüedad","Benjamín","QT.7"),
 ("CB-10","Cobertura de decisiones","JW.3 a JW.5 golpe anticipado, atrasado y nota no golpeada",
  "Golpe antes de la ventana, después de la ventana y ausencia de golpe",
  "Cada una de las tres ramas se ejecuta y produce la clasificación que le corresponde","Benjamín","QT.7"),
 ("CB-11","Cobertura de condiciones","JP.2 sistema de combo",
  "Secuencia de aciertos consecutivos, un fallo intermedio y una racha completa",
  "El combo se incrementa, se reinicia con el fallo y no desborda al alcanzar el máximo","Benjamín","QT.7"),
 ("CB-12","Prueba unitaria","JP.3 cálculo de precisión porcentual",
  "Cero aciertos, todos los aciertos, y una mezcla de aciertos y fallos",
  "El resultado es 0 %, 100 % y el valor esperado. No se produce división entre cero cuando la canción no tiene notas","Benjamín","QT.7"),
 ("CB-13","Cobertura de sentencias","SI.3 volumen espacial del audio",
  "Fuente de audio a distancia mínima, media y máxima respecto del oyente",
  "La atenuación sigue la curva configurada y no produce valores negativos ni saturación","Christian","QT.4"),
 ("CB-14","Cobertura de decisiones","SI selección de muestra por intensidad",
  "Golpes en cada uno de los tres niveles de intensidad, repetidos cinco veces cada uno",
  "Se dispara la muestra del nivel correspondiente y la variación por repetición no reproduce la misma muestra dos veces seguidas","Christian","QT.4"),
]

CAJA_NEGRA = [
 ("CN-01","Particiones de equivalencia","Selección de nivel de dificultad",
  "Cada nivel disponible en el menú",
  "La sesión carga con los parámetros de tempo y tolerancia del nivel elegido","Diana","QT.2"),
 ("CN-02","Transición de estados","Flujo completo de la sesión",
  "Recorrido menú, tutorial, sesión, resultados y regreso al menú",
  "Cada transición ocurre y ningún estado queda sin salida","Diana","QT.3"),
 ("CN-03","Transición de estados","Pausa y reanudación",
  "Pausar a la mitad de una canción y reanudar después de diez segundos",
  "La música y las notas reanudan sincronizadas, sin desfase acumulado","Diana","QT.2"),
 ("CN-04","Pruebas basadas en casos de uso","Abandono de la actividad",
  "Salir a la mitad de la sesión mediante el menú de pausa",
  "Se regresa al menú principal sin cierre inesperado y sin dejar audio sonando","Diana","QT.3"),
 ("CN-05","Análisis de valores límite","Duración de la sesión",
  "Sesión más corta y sesión más larga que el sistema permite configurar",
  "Ambas concluyen correctamente y muestran la pantalla de resultados","Diana","QT.2"),
 ("CN-06","Tabla de decisión","Cálculo del resultado final",
  "Combinaciones de aciertos, fallos y combo máximo alcanzado",
  "El resumen muestra la calificación que corresponde a cada combinación de la tabla","Diana","QT.2"),
 ("CN-07","Adivinación de errores","Golpes simultáneos",
  "Golpear dos componentes al mismo tiempo con ambas baquetas",
  "Ambos golpes se registran de forma independiente, sin que uno cancele al otro","Diana","QT.6"),
 ("CN-08","Adivinación de errores","Golpe fuera de la batería",
  "Mover las baquetas en el aire y golpear el escenario y el suelo",
  "No se registra golpe ni se dispara ningún sonido de batería","Diana","QT.6"),
 ("CN-09","Particiones de equivalencia","Reproducción de audio por componente",
  "Cada componente golpeado en cada uno de los tres niveles de intensidad",
  "El sonido corresponde siempre a la pieza golpeada y su volumen al nivel aplicado","Christian","QT.4"),
 ("CN-10","Pruebas basadas en casos de uso","Tutorial completo",
  "Usuario sin experiencia previa recorre el tutorial de principio a fin",
  "Completa el tutorial sin necesidad de instrucción externa ni del manual","Sarai","QT.3"),
 ("CN-11","Análisis de valores límite","Interfaz a distintas alturas de usuario",
  "Usuario de estatura baja y usuario de estatura alta",
  "Los paneles quedan legibles y alcanzables en ambos casos, sin obligar a movimientos forzados","Sarai","QT.3 · IR.2"),
 ("CN-12","Pruebas basadas en casos de uso","Legibilidad dentro del visor",
  "Lectura de todos los textos de la interfaz con el visor puesto",
  "Todos los textos resultan legibles a la distancia de uso, sin esfuerzo visual","Sarai","IR.1"),
 ("CN-13","Prueba de rendimiento","Cuadros por segundo sostenidos",
  "Sesión completa ejecutada en el visor objetivo",
  "Se sostienen 72 cuadros por segundo, sin caídas por debajo de 60","Misael","QV.3"),
 ("CN-14","Prueba de rendimiento","Latencia entre golpe y sonido",
  "Cien golpes cronometrados con registro de marcas de tiempo",
  "El retardo se mantiene por debajo de 30 ms en el percentil 95 de las mediciones","Misael y Christian","QV.4"),
 ("CN-15","Prueba de estabilidad","Sesión prolongada",
  "Ejecución continua durante treinta minutos",
  "Sin cierres inesperados ni crecimiento sostenido del consumo de memoria","Diana","QV.2"),
 ("CN-16","Prueba de usabilidad","Comodidad de la experiencia",
  "Sesión de quince minutos con cinco usuarios distintos",
  "Ningún participante reporta mareo, fatiga visual ni molestia articular","Sarai y Jesús","QV.5 · QT.8"),
]

# ---- registro ampliado: (id, riesgo, prob, días, impacto en alcance, categoría, estrategia, responsable, disparador, plan)
RIESGOS = [
 ("R1","La latencia entre golpe y sonido supera los 30 ms y obliga a rehacer el sistema de audio",
  0.30,5.0,"Se degrada la respuesta sonora por intensidad","Técnico","Mitigar","Misael",
  "La medición del caso CN-14 arroja un percentil 95 superior a 30 ms.",
  "Sincronizar el audio contra el reloj del sistema de audio y no contra el ciclo de cuadro. Reducir el tamaño del búfer. Si aun así no se alcanza, se acota el alcance del sistema de audio y se documenta la limitación."),
 ("R2","La cadena del entorno tridimensional se retrasa y arrastra la fecha final",
  0.40,4.0,"Ninguno si se absorbe con la reserva de cronograma","Cronograma","Mitigar","Kimberly",
  "Cualquier actividad de la cadena del entorno acumula un día de retraso.",
  "Traslapar la búsqueda de assets con la composición del escenario. Reasignar apoyo temporal de otra área. Es la ruta crítica: se vigila semanalmente."),
 ("R3","La carga del área de QA no cabe en su ventana y obliga a redistribuir trabajo",
  0.60,3.0,"Se recorta documentación no exigida por la materia","Recursos","Mitigar","Benjamín",
  "La carga acumulada de QA supera el 110 % de su ventana disponible.",
  "Redistribuir documentación, evidencias y manuales entre las ocho áreas, dejando en QA solo pruebas y gestión de errores."),
 ("R4","Los recursos con licencia libre resultan insuficientes o de licencia ambigua",
  0.35,2.0,"Se sustituyen por recursos de menor calidad visual o sonora","Externo","Mitigar","Javier y Christian",
  "Un recurso incorporado no tiene licencia verificable.",
  "Verificar y registrar la licencia antes de incorporar cualquier recurso. Mantener una lista de sustitutos."),
 ("R5","La Facultad no concreta el préstamo de los visores",
  0.20,6.0,"Las pruebas con usuarios se reducen a una sola sesión","Externo","Transferir","Benjamín",
  "No hay confirmación escrita del préstamo antes del inicio de la fase de desarrollo.",
  "Obtener confirmación por escrito. Si no se concreta, reducir a un visor aportado por un integrante o solicitar apoyo a otra dependencia."),
 ("R6","Falla o indisponibilidad de un visor durante el proyecto",
  0.15,2.0,"Se pierde la posibilidad de sesiones simultáneas","Externo","Mitigar","Jesús",
  "Un visor presenta fallas o deja de estar disponible.",
  "Mantener el desarrollo ejecutable también en el simulador de escritorio. Reportar la incidencia a la Facultad de inmediato."),
 ("R7","Usuarios de prueba reportan mareo y hay que rehacer la ergonomía",
  0.20,2.0,"Se simplifica el entorno visual","Técnico","Mitigar","Sarai",
  "Un participante reporta molestia durante o después de una sesión.",
  "Aplicar los lineamientos de comodidad desde el diseño: sin movimiento impuesto, interfaz a distancia adecuada, sesiones limitadas. Suspender ante el primer síntoma."),
 ("R8","Pérdida de trabajo por conflicto de versiones en el repositorio",
  0.20,1.5,"Ninguno","Técnico","Mitigar","Diana",
  "Se detecta un conflicto de integración que obliga a rehacer trabajo.",
  "Rama por funcionalidad e integración frecuente. Revisión antes de integrar."),
 ("R9","Un integrante reduce su disponibilidad por carga académica",
  0.45,3.0,"Se redistribuye su trabajo y se recorta alcance secundario","Equipo","Aceptar","Benjamín",
  "Un integrante comunica que su disponibilidad se reduce.",
  "Riesgo inherente a un proyecto académico. Se acepta de forma activa: se reasignan sus actividades y, si hace falta, se recorta alcance conforme a la tolerancia declarada."),
 # --- herramientas e infraestructura
 ("R10","ProjectLibre deja de abrir o corrompe el archivo del cronograma",
  0.25,1.5,"Ninguno sobre el producto; sí sobre el control del proyecto","Herramientas","Mitigar","Diana",
  "El archivo no abre, o abre con datos incompletos.",
  "El cronograma se regenera por completo desde los scripts del proyecto con un solo comando, de modo que el archivo nunca es la única copia. Además se conserva una versión en formato XML, que cualquier herramienta compatible puede leer."),
 ("R11","Pérdida del repositorio o del respaldo del proyecto",
  0.10,8.0,"Pérdida potencial de trabajo no respaldado","Herramientas","Mitigar","Diana",
  "El servicio de alojamiento no responde por más de veinticuatro horas, o se detecta pérdida de historial.",
  "Repositorio remoto más copia local en al menos dos equipos del equipo. Respaldo semanal de los documentos en almacenamiento independiente."),
 ("R12","Falla del equipo de cómputo de un integrante",
  0.30,2.5,"El área afectada se detiene hasta reasignar","Herramientas","Mitigar","el afectado",
  "Un equipo deja de funcionar o pierde capacidad de ejecutar el motor.",
  "Todo el trabajo vive en el repositorio, no en el equipo local. El integrante continúa desde otro equipo o se le reasigna trabajo documental mientras se resuelve."),
 ("R13","Unity o el kit de desarrollo se actualizan y rompen el proyecto",
  0.20,3.0,"Retrabajo en la integración","Herramientas","Evitar","Misael",
  "Una actualización automática cambia la versión del motor o del kit.",
  "Versión del motor y del kit fijada desde el inicio y declarada en el acta. Se desactiva la actualización automática. Ninguna actualización se aplica durante el proyecto."),
 # --- equipo y organización
 ("R14","Un integrante abandona el equipo o da de baja la materia",
  0.15,6.0,"Se pierde o se recorta el área que tenía asignada","Equipo","Mitigar","Benjamín",
  "Un integrante comunica su baja o deja de presentarse dos semanas seguidas.",
  "Cada área tiene un segundo conocedor designado. Se redistribuye el trabajo restante y se recorta alcance secundario del área afectada."),
 ("R15","Un integrante no reporta su avance y el cronograma queda ciego",
  0.50,2.0,"Ninguno directo, pero impide detectar retrasos a tiempo","Equipo","Mitigar","Diana",
  "Un área pasa dos reuniones semanales sin actualizar su estado.",
  "Reporte de avance obligatorio en la reunión semanal. Si un área no reporta, se asume sin avance para efectos de control y se escala al director."),
 ("R16","Choque de carga con exámenes parciales de otras materias",
  0.55,3.0,"Se detiene el avance durante la semana de exámenes","Equipo","Aceptar","Benjamín",
  "Se publica el calendario de parciales y coincide con una semana crítica del proyecto.",
  "Riesgo conocido y no evitable. Se acepta y se compensa adelantando trabajo en las semanas previas. La reserva de cronograma está dimensionada para absorberlo."),
 ("R17","La docente solicita cambios en el alcance o en los entregables",
  0.60,2.5,"Se agrega o se modifica trabajo no previsto","Alcance","Aceptar","Benjamín",
  "Se recibe una indicación que modifica lo acordado.",
  "Ha ocurrido ya varias veces durante el semestre. Se acepta como parte de la naturaleza académica del proyecto. Todo cambio se registra en el control de versiones del documento afectado y se evalúa su impacto sobre el cronograma antes de aceptarlo."),
 ("R18","No se consiguen suficientes usuarios para las pruebas del prototipo",
  0.30,2.0,"Las pruebas con usuarios pierden representatividad","Externo","Mitigar","Jesús",
  "Faltan menos de cinco días para la sesión y hay menos de tres participantes confirmados.",
  "Convocar con dos semanas de anticipación. Como respaldo, recurrir a compañeros de otros equipos de la misma materia."),
]
def emv(r): return r[2]*r[3]
EMV_DIAS = sum(emv(r) for r in RIESGOS)

# ---- ¿el impacto consume reserva de cronograma, o lo absorbe la holgura del área?
# Absorben solo los riesgos cuyo impacto cabe dentro de la holgura del área afectada.
# Holguras mínimas: E 0.00 · A 0.00 · Q 0.00 · J 1.38 · M 1.38 · I 2.00 · D 4.38 · S 5.00
ABSORBIDOS = {"R6","R7","R13"}
EMV_RESERVA = sum(emv(r) for r in RIESGOS if r[0] not in ABSORBIDOS)
def consume(rid): return rid not in ABSORBIDOS

CATEGORIAS = {
 "Técnico":"Rendimiento, latencia, integración y comportamiento del producto.",
 "Cronograma":"Encadenamiento de actividades y puntos de convergencia de la red.",
 "Recursos":"Disponibilidad y carga de trabajo de las personas.",
 "Externo":"Dependencias fuera del control del equipo.",
 "Herramientas":"Software, equipo de cómputo e infraestructura de trabajo.",
 "Equipo":"Disponibilidad, permanencia y coordinación de los integrantes.",
 "Alcance":"Cambios en lo que se espera entregar.",
}

if __name__ == "__main__":
    print(f"casos de caja blanca: {len(CAJA_BLANCA)}")
    print(f"casos de caja negra : {len(CAJA_NEGRA)}")
    print(f"total de casos      : {len(CAJA_BLANCA)+len(CAJA_NEGRA)}")
    print(f"riesgos             : {len(RIESGOS)}   EMV {EMV_DIAS:.2f} días")
    from collections import Counter
    print()
    for c,n in Counter(r[5] for r in RIESGOS).most_common(): print(f"  {c:<14}{n}")
    print()
    for q,n in Counter(x[5] for x in CAJA_BLANCA+CAJA_NEGRA).most_common(): print(f"  {q:<22}{n} casos")
